

Thu Apr 23 16:08:53.360 UTC
Building configuration...
!! IOS XR Configuration 7.9.2
!! Last configuration change at Thu Apr 23 15:40:26 2026 by root
!
hostname mpe1
username root
 group root-lr
 group cisco-support
 secret 10 $6$Wa39l/NlGQg25l/.$5iSGuMOk4yj1gmhOPswBwG/w2Bx4ZUVApt2uZ1pZTPfvofGd1Umhowu.a/GB5lp1ITiWeBRWnYOuNaBI2KqVx.
!
line default
 transport input all
 transport output all
!
call-home
 service active
 contact smart-licensing
 profile CiscoTAC-1
  active
  destination transport-method email disable
  destination transport-method http
 !
!
interface Loopback0
 ipv4 address 100.0.0.15 255.255.255.255
 ipv6 address 2001:cafe::f/128
!
interface MgmtEth0/RP0/CPU0/0
 ipv4 address 10.39.51.222 255.255.224.0
!
interface GigabitEthernet0/0/0/1
 description private22 :: mpe1 -- jpe1
 ipv4 address 100.1.0.90 255.255.255.252
 ipv6 address 2001:cafe:1:16::2/64
!
interface GigabitEthernet0/0/0/2
 description private24 :: mpe1 -- pp1
 ipv4 address 100.1.0.98 255.255.255.252
 ipv6 address 2001:cafe:1:18::2/64
!
interface GigabitEthernet0/0/0/3
 description private26 :: mpe1 -- ce1
 ipv4 address 100.1.0.105 255.255.255.252
 ipv6 address 2001:cafe:1:1a::1/64
!
router static
 address-family ipv4 unicast
  10.0.0.0/8 MgmtEth0/RP0/CPU0/0 10.39.63.254
  66.129.255.62/32 MgmtEth0/RP0/CPU0/0 10.39.63.254
  172.16.0.0/12 MgmtEth0/RP0/CPU0/0 10.39.63.254
 !
!
router isis bb
 is-type level-2-only
 net 49.0001.0001.6400.000f.00
 address-family ipv4 unicast
  metric-style wide
 !
 interface Loopback0
  passive
  address-family ipv4 unicast
  !
 !
 interface GigabitEthernet0/0/0/2
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !
 !
!
router bgp 2
 bgp router-id 100.0.0.16
 bgp graceful-restart
 bgp log neighbor changes detail
 address-family ipv4 unicast
 !
 address-family vpnv4 unicast
 !
 address-family vpnv6 unicast
 !
 address-family l2vpn vpls-vpws
 !
 session-group RR_SESSION
  remote-as 2
  update-source Loopback0
 !
 neighbor-group RR
  use session-group RR_SESSION
  address-family ipv4 unicast
  !
  address-family vpnv4 unicast
  !
  address-family vpnv6 unicast
  !
  address-family l2vpn vpls-vpws
  !
 !
 neighbor 100.0.0.4
  use neighbor-group RR
 !
!
mpls ldp
 log
  neighbor
 !
 igp sync delay on-session-up 20
 router-id 100.0.0.15
 session protection
 address-family ipv4
  discovery targeted-hello accept
  label
   local
    allocate for host-routes
   !
  !
 !
 interface GigabitEthernet0/0/0/2
 !
!
telnet vrf default ipv4 server max-servers 10
ssh server v2
end

