

Thu Apr 23 16:09:47.694 UTC
Building configuration...
!! IOS XR Configuration 7.9.2
!! Last configuration change at Thu Apr 23 15:25:26 2026 by root
!
hostname pp1
username root
 group root-lr
 group cisco-support
 secret 10 $6$0hnCB1vgHnvoAB1.$dxVrUBKqWsoexboaQmD00EcgLGRB0tV8icoYQDdWbaI00sS7zw6KWpu3A1mojeNcNWYhWCacmcMSJ9RMMqJog.
!
line default
 transport input all
 transport output all
!
call-home
 service active
 contact smart-licensing
 profile CiscoTAC-1
  active
  destination transport-method email disable
  destination transport-method http
 !
!
interface Loopback0
 ipv4 address 100.0.0.2 255.255.255.255
 ipv6 address 2001:cafe::2/128
!
interface MgmtEth0/RP0/CPU0/0
 ipv4 address 10.39.51.221 255.255.224.0
!
interface GigabitEthernet0/0/0/1
 description private0 :: pp1 -- rrf
 ipv4 address 100.1.0.2 255.255.255.252
 ipv6 address 2001:cafe:1::2/64
!
interface GigabitEthernet0/0/0/2
 description private2 :: pp1 -- rrm
 ipv4 address 100.1.0.10 255.255.255.252
 ipv6 address 2001:cafe:1:2::2/64
!
interface GigabitEthernet0/0/0/3
 description private4 :: pp1 -- pp2
 ipv4 address 100.1.0.17 255.255.255.252
 ipv6 address 2001:cafe:1:4::1/64
!
interface GigabitEthernet0/0/0/4
 description private5 :: pp1 -- pp3
 ipv4 address 100.1.0.21 255.255.255.252
 ipv6 address 2001:cafe:1:5::1/64
!
interface GigabitEthernet0/0/0/5
 description private18 :: pp1 -- jpe1
 ipv4 address 100.1.0.74 255.255.255.252
 ipv6 address 2001:cafe:1:12::2/64
!
interface GigabitEthernet0/0/0/6
 description private24 :: pp1 -- mpe1
 ipv4 address 100.1.0.97 255.255.255.252
 ipv6 address 2001:cafe:1:18::1/64
!
router static
 address-family ipv4 unicast
  10.0.0.0/8 MgmtEth0/RP0/CPU0/0 10.39.63.254
  66.129.255.62/32 MgmtEth0/RP0/CPU0/0 10.39.63.254
  172.16.0.0/12 MgmtEth0/RP0/CPU0/0 10.39.63.254
 !
!
router isis bb
 is-type level-2-only
 net 49.0001.0001.6400.0002.00
 address-family ipv4 unicast
  metric-style wide
 !
 interface Loopback0
  passive
  address-family ipv4 unicast
  !
 !
 interface GigabitEthernet0/0/0/1
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !
 !
 interface GigabitEthernet0/0/0/2
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !
 !
 interface GigabitEthernet0/0/0/3
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !
 !
 interface GigabitEthernet0/0/0/4
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !
 !
 interface GigabitEthernet0/0/0/5
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !
 !
 interface GigabitEthernet0/0/0/6
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !
 !
!
mpls ldp
 log
  neighbor
 !
 igp sync delay on-session-up 20
 router-id 100.0.0.2
 session protection
 address-family ipv4
  discovery targeted-hello accept
  label
   local
    allocate for host-routes
   !
  !
 !
 interface GigabitEthernet0/0/0/1
 !
 interface GigabitEthernet0/0/0/2
 !
 interface GigabitEthernet0/0/0/3
 !
 interface GigabitEthernet0/0/0/4
 !
 interface GigabitEthernet0/0/0/5
 !
 interface GigabitEthernet0/0/0/6
 !
!
ssh server v2
telnet vrf default ipv4 server max-servers 10
end

