

Thu Apr 23 16:09:50.655 UTC
Building configuration...
!! IOS XR Configuration 7.9.2
!! Last configuration change at Thu Apr 23 15:26:49 2026 by root
!
hostname pp4
username root
 group root-lr
 group cisco-support
 secret 10 $6$doqnJ0hxQZDL7J0.$W73Ux1XS8tRYo4y703jMr/fnXijeozkVbcK4qA3IzZltlVDwmB0cz.H0b50hVB3fTtXCpFtKOQDkLv/jvbU21/
!
line default
 transport input all
 transport output all
!
call-home
 service active
 contact smart-licensing
 profile CiscoTAC-1
  active
  destination transport-method email disable
  destination transport-method http
 !
!
interface Loopback0
 ipv4 address 100.0.0.6 255.255.255.255
 ipv6 address 2001:cafe::6/128
!
interface MgmtEth0/RP0/CPU0/0
 ipv4 address 10.39.51.200 255.255.224.0
!
interface GigabitEthernet0/0/0/1
 description private6 :: pp4 -- pp2
 ipv4 address 100.1.0.26 255.255.255.252
 ipv6 address 2001:cafe:1:6::2/64
!
interface GigabitEthernet0/0/0/2
 description private7 :: pp4 -- pp3
 ipv4 address 100.1.0.30 255.255.255.252
 ipv6 address 2001:cafe:1:7::2/64
!
interface GigabitEthernet0/0/0/3
 description private21 :: pp4 -- jpe4
 ipv4 address 100.1.0.86 255.255.255.252
 ipv6 address 2001:cafe:1:15::2/64
!
router static
 address-family ipv4 unicast
  10.0.0.0/8 MgmtEth0/RP0/CPU0/0 10.39.63.254
  66.129.255.62/32 MgmtEth0/RP0/CPU0/0 10.39.63.254
  172.16.0.0/12 MgmtEth0/RP0/CPU0/0 10.39.63.254
 !
!
router isis bb
 is-type level-2-only
 net 49.0001.0001.6400.0006.00
 address-family ipv4 unicast
  metric-style wide
 !
 interface Loopback0
  passive
  address-family ipv4 unicast
  !
 !
 interface GigabitEthernet0/0/0/1
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !
 !
 interface GigabitEthernet0/0/0/2
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !
 !
 interface GigabitEthernet0/0/0/3
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !
 !
!
mpls ldp
 log
  neighbor
 !
 igp sync delay on-session-up 20
 router-id 100.0.0.6
 session protection
 address-family ipv4
  discovery targeted-hello accept
  label
   local
    allocate for host-routes
   !
  !
 !
 interface GigabitEthernet0/0/0/1
 !
 interface GigabitEthernet0/0/0/2
 !
 interface GigabitEthernet0/0/0/3
 !
!
telnet vrf default ipv4 server max-servers 10
ssh server v2
end

