

Thu Apr 23 16:09:54.303 UTC
Building configuration...
!! IOS XR Configuration 7.9.2
!! Last configuration change at Thu Apr 23 15:32:44 2026 by root
!
hostname tgw2
username root
 group root-lr
 group cisco-support
 secret 10 $6$iL4a20ZV7VMG620.$7Q5EcgXuBmKESzjkGiYvQI2kupKcouedJZ.dmpxU1RKqyV8QXdjZfWyQxbu9s8SJvYg64PvQO9LEdfVyqoHnv.
!
line default
 transport input all
 transport output all
!
call-home
 service active
 contact smart-licensing
 profile CiscoTAC-1
  active
  destination transport-method email disable
  destination transport-method http
 !
!
interface Loopback0
 ipv4 address 100.0.0.8 255.255.255.255
 ipv6 address 2001:cafe::8/128
!
interface MgmtEth0/RP0/CPU0/0
 ipv4 address 10.39.52.23 255.255.224.0
!
interface GigabitEthernet0/0/0/1
 description private8 :: tgw2 -- tgw1
 ipv4 address 100.1.0.34 255.255.255.252
 ipv6 address 2001:cafe:1:8::2/64
!
interface GigabitEthernet0/0/0/2
 description private10 :: tgw2 -- tgw4
 ipv4 address 100.1.0.41 255.255.255.252
 ipv6 address 2001:cafe:1:a::1/64
!
interface GigabitEthernet0/0/0/3
 description private13 :: tgw2 -- jpe2
 ipv4 address 100.1.0.53 255.255.255.252
 ipv6 address 2001:cafe:1:d::1/64
!
router static
 address-family ipv4 unicast
  10.0.0.0/8 MgmtEth0/RP0/CPU0/0 10.39.63.254
  66.129.255.62/32 MgmtEth0/RP0/CPU0/0 10.39.63.254
  172.16.0.0/12 MgmtEth0/RP0/CPU0/0 10.39.63.254
 !
!
router isis bb
 is-type level-2-only
 net 49.0001.0001.6400.0008.00
 address-family ipv4 unicast
  metric-style wide
 !
 interface Loopback0
  passive
  address-family ipv4 unicast
  !
 !
 interface GigabitEthernet0/0/0/1
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !
 !
 interface GigabitEthernet0/0/0/2
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !
 !
!
mpls ldp
 log
  neighbor
 !
 igp sync delay on-session-up 20
 router-id 100.0.0.8
 session protection
 address-family ipv4
  discovery targeted-hello accept
  label
   local
    allocate for host-routes
   !
  !
 !
 interface GigabitEthernet0/0/0/1
 !
 interface GigabitEthernet0/0/0/2
 !
!
telnet vrf default ipv4 server max-servers 10
ssh server v2
end

