

Thu Apr 23 16:09:55.422 UTC
Building configuration...
!! IOS XR Configuration 7.9.2
!! Last configuration change at Thu Apr 23 15:41:19 2026 by root
!
hostname tgw3
username root
 group root-lr
 group cisco-support
 secret 10 $6$RaFV/0NIMU346/0.$kCrKSy89kJ32yaihZ.Qc25pUPiQ1B4IOOF2ndu2.PkSinCe0DLmM51F1YDuhS2hhD4yQOjbRZdoqL.KFoWDWm1
!
line default
 transport input all
 transport output all
!
call-home
 service active
 contact smart-licensing
 profile CiscoTAC-1
  active
  destination transport-method email disable
  destination transport-method http
 !
!
interface Loopback0
 ipv4 address 100.0.0.9 255.255.255.255
 ipv6 address 2001:cafe::9/128
!
interface MgmtEth0/RP0/CPU0/0
 ipv4 address 10.39.52.43 255.255.224.0
!
interface GigabitEthernet0/0/0/1
 description private9 :: tgw3 -- tgw1
 ipv4 address 100.1.0.38 255.255.255.252
 ipv6 address 2001:cafe:1:9::2/64
!
interface GigabitEthernet0/0/0/2
 description private11 :: tgw3 -- tgw4
 ipv4 address 100.1.0.45 255.255.255.252
 ipv6 address 2001:cafe:1:b::1/64
!
interface GigabitEthernet0/0/0/3
 description private14 :: tgw3 -- jpe3
 ipv4 address 100.1.0.57 255.255.255.252
 ipv6 address 2001:cafe:1:e::1/64
!
router static
 address-family ipv4 unicast
  10.0.0.0/8 MgmtEth0/RP0/CPU0/0 10.39.63.254
  66.129.255.62/32 MgmtEth0/RP0/CPU0/0 10.39.63.254
  172.16.0.0/12 MgmtEth0/RP0/CPU0/0 10.39.63.254
 !
!
router isis bb
 is-type level-2-only
 net 49.0001.0001.6400.0009.00
 address-family ipv4 unicast
  metric-style wide
 !
 interface Loopback0
  passive
  address-family ipv4 unicast
  !
 !
 interface GigabitEthernet0/0/0/2
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !
 !
!
mpls ldp
 log
  neighbor
 !
 igp sync delay on-session-up 20
 router-id 100.0.0.9
 session protection
 address-family ipv4
  discovery targeted-hello accept
  label
   local
    allocate for host-routes
   !
  !
 !
 interface GigabitEthernet0/0/0/2
 !
!
ssh server v2
telnet vrf default ipv4 server max-servers 10
end

