

Thu Apr 23 16:09:55.900 UTC
Building configuration...
!! IOS XR Configuration 7.9.2
!! Last configuration change at Thu Apr 23 15:33:20 2026 by root
!
hostname tgw4
username root
 group root-lr
 group cisco-support
 secret 10 $6$DAzh21nT9lrGA21.$bM4kkN8I6zK1AHDN7l0A6aIhI9MZ82p4YvC4vc7X7QlB1uRKk9vA/mdjeFAGkVPVyHjxkWcYSmRh7jNJTtXv90
!
line default
 transport input all
 transport output all
!
call-home
 service active
 contact smart-licensing
 profile CiscoTAC-1
  active
  destination transport-method email disable
  destination transport-method http
 !
!
interface Loopback0
 ipv4 address 100.0.0.10 255.255.255.255
 ipv6 address 2001:cafe::a/128
!
interface MgmtEth0/RP0/CPU0/0
 ipv4 address 10.39.51.132 255.255.224.0
!
interface GigabitEthernet0/0/0/1
 description private10 :: tgw4 -- tgw2
 ipv4 address 100.1.0.42 255.255.255.252
 ipv6 address 2001:cafe:1:a::2/64
!
interface GigabitEthernet0/0/0/2
 description private11 :: tgw4 -- tgw3
 ipv4 address 100.1.0.46 255.255.255.252
 ipv6 address 2001:cafe:1:b::2/64
!
interface GigabitEthernet0/0/0/3
 description private15 :: tgw4 -- jpe4
 ipv4 address 100.1.0.61 255.255.255.252
 ipv6 address 2001:cafe:1:f::1/64
!
router static
 address-family ipv4 unicast
  10.0.0.0/8 MgmtEth0/RP0/CPU0/0 10.39.63.254
  66.129.255.62/32 MgmtEth0/RP0/CPU0/0 10.39.63.254
  172.16.0.0/12 MgmtEth0/RP0/CPU0/0 10.39.63.254
 !
!
router isis bb
 is-type level-2-only
 net 49.0001.0001.6400.000a.00
 address-family ipv4 unicast
  metric-style wide
 !
 interface Loopback0
  passive
  address-family ipv4 unicast
  !
 !
 interface GigabitEthernet0/0/0/1
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !
 !
 interface GigabitEthernet0/0/0/2
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !
 !
!
mpls ldp
 log
  neighbor
 !
 igp sync delay on-session-up 20
 router-id 100.0.0.10
 session protection
 address-family ipv4
  discovery targeted-hello accept
  label
   local
    allocate for host-routes
   !
  !
 !
 interface GigabitEthernet0/0/0/1
 !
 interface GigabitEthernet0/0/0/2
 !
!
ssh server v2
telnet vrf default ipv4 server max-servers 10
end

