interfaces {
    lo0 {
        unit 0 {
            family inet {
                address 100.64.0.15/32;
            }
            family iso {
                address 49.0001.0001.6440.000f.00;
            }
	    family mpls;
        }
    }
    ge-0/0/1 {
        description "private20 :: internet -- jpe1";
        unit 0 {
            family inet {
                address 100.100.20.2/24;
            }
        }
    }
    ge-0/0/2 {
        description "private21 :: internet -- pe1";
        unit 0 {
            family inet {
                address 100.100.21.2/24;
            }
        }
    }
    ge-0/0/3 {
        description "private22 :: internet -- pe2";
        unit 0 {
            family inet {
                address 100.100.22.2/24;
            }
        }
    }
    ge-0/0/4 {
        description "private23 :: internet -- jpe2";
        unit 0 {
            family inet {
                address 100.100.23.2/24;
            }
        }
    }
    ge-0/0/5 {
        description "private24 :: internet -- tgw1";
        unit 0 {
            family inet {
                address 100.100.24.2/24;
            }
        }
    }
    ge-0/0/6 {
        description "private25 :: internet -- tgw2";
        unit 0 {
            family inet {
                address 100.100.25.2/24;
            }
        }
    }
}
system {
    static-host-mapping {
        cm1 {
            inet [  100.64.0.13  100.100.16.2  ];
        }
        cm2 {
            inet [  100.64.0.14  100.100.17.2  ];
        }
        internet {
            inet [  100.64.0.15  100.100.20.2  100.100.21.2  100.100.22.2  100.100.23.2  100.100.24.2  100.100.25.2  ];
        }
        jpe1 {
            inet [  100.64.0.5  100.100.2.1  100.100.3.1  100.100.9.1  100.100.13.1  100.100.20.1  ];
        }
        jpe2 {
            inet [  100.64.0.6  100.100.2.2  100.100.4.1  100.100.10.1  100.100.14.1  100.100.23.1  ];
        }
        mpe1 {
            inet [  100.64.0.9  100.100.11.2  100.100.16.1  100.100.18.1  ];
        }
        mpe2 {
            inet [  100.64.0.10  100.100.12.2  100.100.17.1  100.100.19.1  ];
        }
        pe1 {
            inet [  100.64.0.7  100.100.3.2  100.100.5.1  100.100.6.1  100.100.18.2  100.100.21.1  ];
        }
        pe2 {
            inet [  100.64.0.8  100.100.4.2  100.100.5.2  100.100.7.1  100.100.19.2  100.100.22.1  ];
        }
        pp1 {
            inet [  100.64.0.2  100.100.0.2  100.100.6.2  100.100.8.1  100.100.9.2  100.100.11.1  ];
        }
        pp2 {
            inet [  100.64.0.4  100.100.1.2  100.100.7.2  100.100.8.2  100.100.10.2  100.100.12.1  ];
        }
        rr1 {
            inet [  100.64.0.1  100.100.0.1  ];
        }
        rr2 {
            inet [  100.64.0.3  100.100.1.1  ];
        }
        tgw1 {
            inet [  100.64.0.11  100.100.13.2  100.100.15.1  100.100.24.1  ];
        }
        tgw2 {
            inet [  100.64.0.12  100.100.14.2  100.100.15.2  100.100.25.1  ];
        }
    }
}
routing-options {
    router-id 100.64.0.15;
}
system {
    root-authentication {
        ssh-rsa "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAIEAndoan2TzmZp3J3UJjlXksF1DcJhntlLTs9mEVkY/0sTXTgqe75cVB9cwOY8Vsj9l3p6yOpO0cMwbxiWmLmnYzBDoeyTAKzFLr/Ccdm0NhMLFnP/pyewShQJNOJLPCERNxAWCQlrQnXE+UvqrY45fOQc4NnHhggBK3IdB6AcHOn8=";
    }
    services ssh root-login allow;
}
