hostname pe1
!
interface Loopback0
 ipv4 address 100.64.0.7 255.255.255.255
!
interface GigabitEthernet0/0/0/1
 description private3 :: pe1 -- jpe1
 ipv4 address 100.100.3.2/24
!
interface GigabitEthernet0/0/0/2
 description private5 :: pe1 -- pe2
 ipv4 address 100.100.5.1/24
!
interface GigabitEthernet0/0/0/3
 description private6 :: pe1 -- pp1
 ipv4 address 100.100.6.1/24
!
interface GigabitEthernet0/0/0/4
 description private18 :: pe1 -- mpe1
 ipv4 address 100.100.18.2/24
!
interface GigabitEthernet0/0/0/5
 description private21 :: pe1 -- internet
 ipv4 address 100.100.21.1/24
!

!
router isis bb
 is-type level-2-only
 net 49.0001.0001.6440.0007.00
 address-family ipv4 unicast
  metric-style wide
 !
 interface Loopback0
  passive
  address-family ipv4 unicast
 !
!
 interface GigabitEthernet0/0/0/1
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !
 interface GigabitEthernet0/0/0/2
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !
 interface GigabitEthernet0/0/0/3
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !

!
mpls ldp
 log
  neighbor
 !
 igp sync delay on-session-up 20
 router-id 100.64.0.7
 session protection
 address-family ipv4
  discovery targeted-hello accept
  label
   local
    allocate for host-routes
   !
  !
 !
 interface GigabitEthernet0/0/0/1
 interface GigabitEthernet0/0/0/2
 interface GigabitEthernet0/0/0/3

!
router bgp 15924
 bgp router-id 100.64.0.7
 bgp graceful-restart
 bgp log neighbor changes detail
!
 address-family ipv4 unicast
!
 address-family vpnv4 unicast
!
 address-family vpnv6 unicast
!
 address-family l2vpn vpls-vpws
!

!
 session-group RR_SESSION
  remote-as 15924
  update-source Loopback0
!
 neighbor-group RR
  use session-group RR_SESSION
!
 address-family ipv4 unicast
!
 address-family vpnv4 unicast
!
 address-family vpnv6 unicast
!
 address-family l2vpn vpls-vpws
!

!
 neighbor 100.64.0.1
  use neighbor-group RR
 !
 neighbor 100.64.0.3
  use neighbor-group RR
 !
