hostname pe2
!
interface Loopback0
 ipv4 address 100.64.0.8 255.255.255.255
!
interface GigabitEthernet0/0/0/1
 description private4 :: pe2 -- jpe2
 ipv4 address 100.100.4.2/24
!
interface GigabitEthernet0/0/0/2
 description private5 :: pe2 -- pe1
 ipv4 address 100.100.5.2/24
!
interface GigabitEthernet0/0/0/3
 description private7 :: pe2 -- pp2
 ipv4 address 100.100.7.1/24
!
interface GigabitEthernet0/0/0/4
 description private19 :: pe2 -- mpe2
 ipv4 address 100.100.19.2/24
!
interface GigabitEthernet0/0/0/5
 description private22 :: pe2 -- internet
 ipv4 address 100.100.22.1/24
!

!
router isis bb
 is-type level-2-only
 net 49.0001.0001.6440.0008.00
 address-family ipv4 unicast
  metric-style wide
 !
 interface Loopback0
  passive
  address-family ipv4 unicast
 !
!
 interface GigabitEthernet0/0/0/1
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !
 interface GigabitEthernet0/0/0/2
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !
 interface GigabitEthernet0/0/0/3
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !

!
mpls ldp
 log
  neighbor
 !
 igp sync delay on-session-up 20
 router-id 100.64.0.8
 session protection
 address-family ipv4
  discovery targeted-hello accept
  label
   local
    allocate for host-routes
   !
  !
 !
 interface GigabitEthernet0/0/0/1
 interface GigabitEthernet0/0/0/2
 interface GigabitEthernet0/0/0/3

!
router bgp 15924
 bgp router-id 100.64.0.8
 bgp graceful-restart
 bgp log neighbor changes detail
!
 address-family ipv4 unicast
!
 address-family vpnv4 unicast
!
 address-family vpnv6 unicast
!
 address-family l2vpn vpls-vpws
!

!
 session-group RR_SESSION
  remote-as 15924
  update-source Loopback0
!
 neighbor-group RR
  use session-group RR_SESSION
!
 address-family ipv4 unicast
!
 address-family vpnv4 unicast
!
 address-family vpnv6 unicast
!
 address-family l2vpn vpls-vpws
!

!
 neighbor 100.64.0.1
  use neighbor-group RR
 !
 neighbor 100.64.0.3
  use neighbor-group RR
 !
