hostname rr2
!
interface Loopback0
 ipv4 address 100.64.0.3 255.255.255.255
!
interface GigabitEthernet0/0/0/1
 description private1 :: rr2 -- pp2
 ipv4 address 100.100.1.1/24
!

!
router isis bb
 is-type level-2-only
 net 49.0001.0001.6440.0003.00
 address-family ipv4 unicast
  metric-style wide
 !
 interface Loopback0
  passive
  address-family ipv4 unicast
 !
!
 interface GigabitEthernet0/0/0/1
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !

!
mpls ldp
 log
  neighbor
 !
 igp sync delay on-session-up 20
 router-id 100.64.0.3
 session protection
 address-family ipv4
  discovery targeted-hello accept
  label
   local
    allocate for host-routes
   !
  !
 !
 interface GigabitEthernet0/0/0/1

!
