spawn ~/bin/ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no rr2 show running
Warning: Permanently added '10.54.145.5' (ED25519) to the list of known hosts.
(root@10.54.145.5) Password: 
al

Fri Jun 26 14:02:56.236 UTC
Building configuration...
!! IOS XR Configuration 7.9.2
!! Last configuration change at Thu Jun 25 10:24:29 2026 by root
!
hostname rr2
username root
 group root-lr
 group cisco-support
 secret 10 $6$cbkQr/7ArRnR5r/.$VJRNzTirfhYUddmevZjNbqIFL0cfJcRavz.iE7R2dwn8xOd8NW98GIs/oAQ/TTA3lHxw3Fm4bh6PO2roC0cYN.
!
line default
 transport input all
 transport output all
!
key chain ISIS-LSP
 key 1
  accept-lifetime 00:01:00 january 01 2011 infinite
  key-string password 05000E18794846024D5631
  send-lifetime 00:01:00 january 01 2011 infinite
  cryptographic-algorithm HMAC-MD5
 !
 accept-tolerance infinite
!
key chain ISIS-HELLO
 key 1
  accept-lifetime 00:01:00 january 01 2011 infinite
  key-string password 01180E13030F0E04751F68
  send-lifetime 00:01:00 january 01 2011 infinite
  cryptographic-algorithm HMAC-MD5
 !
 accept-tolerance infinite
!
call-home
 service active
 contact smart-licensing
 profile CiscoTAC-1
  active
  destination transport-method email disable
  destination transport-method http
 !
!
interface Loopback0
 ipv4 address 100.64.0.3 255.255.255.255
 ipv6 address 2001:cafe::3/128
!
interface MgmtEth0/RP0/CPU0/0
 ipv4 address 10.54.145.5 255.255.224.0
!
interface GigabitEthernet0/0/0/1
 description private1 :: rr2 -- pp2
 ipv4 address 100.100.1.1 255.255.255.0
!
router static
 address-family ipv4 unicast
  10.0.0.0/8 MgmtEth0/RP0/CPU0/0 10.54.159.254
  66.129.255.62/32 MgmtEth0/RP0/CPU0/0 10.54.159.254
  172.16.0.0/12 MgmtEth0/RP0/CPU0/0 10.54.159.254
 !
!
router isis bb
 net 49.0001.0001.6440.0003.00
 log adjacency changes
 lsp-gen-interval initial-wait 100 secondary-wait 100 maximum-wait 1000
 lsp-refresh-interval 65000
 max-lsp-lifetime 65535
 lsp-password keychain ISIS-LSP
 address-family ipv4 unicast
  metric-style wide
  metric-style wide level 2
  maximum-paths 1
 !
 interface Loopback0
  passive
  address-family ipv4 unicast
  !
 !
 interface GigabitEthernet0/0/0/1
  circuit-type level-2-only
  point-to-point
  hello-padding disable
  hello-password keychain ISIS-HELLO
  address-family ipv4 unicast
   metric 1000 level 2
  !
 !
!
router bgp 15924
 bgp router-id 100.64.0.3
 bgp cluster-id 100.64.0.3
 address-family ipv4 unicast
  allocate-label all
 !
 address-family vpnv4 unicast
 !
 address-family ipv6 unicast
  allocate-label all
 !
 address-family vpnv6 unicast
 !
 neighbor-group RRC
  remote-as 15924
  update-source Loopback0
  address-family ipv4 unicast
   route-reflector-client
  !
  address-family ipv4 labeled-unicast
   route-reflector-client
  !
  address-family vpnv4 unicast
   route-reflector-client
  !
  address-family ipv6 unicast
   route-reflector-client
  !
  address-family ipv6 labeled-unicast
   route-reflector-client
  !
  address-family vpnv6 unicast
   route-reflector-client
  !
 !
 neighbor 100.64.0.1
  remote-as 15924
  update-source Loopback0
  address-family ipv4 unicast
  !
  address-family vpnv4 unicast
  !
  address-family ipv6 labeled-unicast
  !
  address-family vpnv6 unicast
  !
 !
 neighbor 100.64.0.5
  use neighbor-group RRC
 !
 neighbor 100.64.0.6
  use neighbor-group RRC
 !
 neighbor 100.64.0.7
  use neighbor-group RRC
 !
 neighbor 100.64.0.8
  use neighbor-group RRC
 !
 neighbor 100.64.0.254
  use neighbor-group RRC
 !
!
lldp
!
ssh server v2
telnet vrf default ipv4 server max-servers 10
end

