hostname pp1
!
interface Loopback0
 ipv4 address 100.0.0.2 255.255.255.255
 ipv6 address 2001:cafe::2/128
!
interface GigabitEthernet0/0/0/1
 description private0 :: pp1 -- rrf
 ipv4 address 100.1.0.2/30
 ipv6 address 2001:cafe:1::2/64
!
interface GigabitEthernet0/0/0/2
 description private2 :: pp1 -- rrm
 ipv4 address 100.1.0.10/30
 ipv6 address 2001:cafe:1:2::2/64
!
interface GigabitEthernet0/0/0/3
 description private4 :: pp1 -- pp2
 ipv4 address 100.1.0.17/30
 ipv6 address 2001:cafe:1:4::1/64
!
interface GigabitEthernet0/0/0/4
 description private5 :: pp1 -- pp3
 ipv4 address 100.1.0.21/30
 ipv6 address 2001:cafe:1:5::1/64
!
interface GigabitEthernet0/0/0/5
 description private18 :: pp1 -- jpe1
 ipv4 address 100.1.0.74/30
 ipv6 address 2001:cafe:1:12::2/64
!
interface GigabitEthernet0/0/0/6
 description private24 :: pp1 -- mpe1
 ipv4 address 100.1.0.97/30
 ipv6 address 2001:cafe:1:18::1/64
!

!
router isis bb
 is-type level-2-only
 net 49.0001.0001.6400.0002.00
 address-family ipv4 unicast
  metric-style wide
 !
 interface Loopback0
  passive
  address-family ipv4 unicast
 !
!
 interface GigabitEthernet0/0/0/1
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !
 interface GigabitEthernet0/0/0/2
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !
 interface GigabitEthernet0/0/0/3
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !
 interface GigabitEthernet0/0/0/4
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !
 interface GigabitEthernet0/0/0/5
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !
 interface GigabitEthernet0/0/0/6
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !

!
mpls ldp
 log
  neighbor
 !
 igp sync delay on-session-up 20
 router-id 100.0.0.2
 session protection
 address-family ipv4
  discovery targeted-hello accept
  label
   local
    allocate for host-routes
   !
  !
 !
 interface GigabitEthernet0/0/0/1
 interface GigabitEthernet0/0/0/2
 interface GigabitEthernet0/0/0/3
 interface GigabitEthernet0/0/0/4
 interface GigabitEthernet0/0/0/5
 interface GigabitEthernet0/0/0/6

!
