hostname pp3
!
interface Loopback0
 ipv4 address 100.0.0.5 255.255.255.255
 ipv6 address 2001:cafe::5/128
!
interface GigabitEthernet0/0/0/1
 description private5 :: pp3 -- pp1
 ipv4 address 100.1.0.22/30
 ipv6 address 2001:cafe:1:5::2/64
!
interface GigabitEthernet0/0/0/2
 description private7 :: pp3 -- pp4
 ipv4 address 100.1.0.29/30
 ipv6 address 2001:cafe:1:7::1/64
!
interface GigabitEthernet0/0/0/3
 description private20 :: pp3 -- jpe3
 ipv4 address 100.1.0.82/30
 ipv6 address 2001:cafe:1:14::2/64
!
interface GigabitEthernet0/0/0/4
 description private25 :: pp3 -- mpe3
 ipv4 address 100.1.0.101/30
 ipv6 address 2001:cafe:1:19::1/64
!

!
router isis bb
 is-type level-2-only
 net 49.0001.0001.6400.0005.00
 address-family ipv4 unicast
  metric-style wide
 !
 interface Loopback0
  passive
  address-family ipv4 unicast
 !
!
 interface GigabitEthernet0/0/0/1
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !
 interface GigabitEthernet0/0/0/2
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !
 interface GigabitEthernet0/0/0/3
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !
 interface GigabitEthernet0/0/0/4
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !

!
mpls ldp
 log
  neighbor
 !
 igp sync delay on-session-up 20
 router-id 100.0.0.5
 session protection
 address-family ipv4
  discovery targeted-hello accept
  label
   local
    allocate for host-routes
   !
  !
 !
 interface GigabitEthernet0/0/0/1
 interface GigabitEthernet0/0/0/2
 interface GigabitEthernet0/0/0/3
 interface GigabitEthernet0/0/0/4

!
