hostname pp4
!
interface Loopback0
 ipv4 address 100.0.0.6 255.255.255.255
 ipv6 address 2001:cafe::6/128
!
interface GigabitEthernet0/0/0/1
 description private6 :: pp4 -- pp2
 ipv4 address 100.1.0.26/30
 ipv6 address 2001:cafe:1:6::2/64
!
interface GigabitEthernet0/0/0/2
 description private7 :: pp4 -- pp3
 ipv4 address 100.1.0.30/30
 ipv6 address 2001:cafe:1:7::2/64
!
interface GigabitEthernet0/0/0/3
 description private21 :: pp4 -- jpe4
 ipv4 address 100.1.0.86/30
 ipv6 address 2001:cafe:1:15::2/64
!

!
router isis bb
 is-type level-2-only
 net 49.0001.0001.6400.0006.00
 address-family ipv4 unicast
  metric-style wide
 !
 interface Loopback0
  passive
  address-family ipv4 unicast
 !
!
 interface GigabitEthernet0/0/0/1
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !
 interface GigabitEthernet0/0/0/2
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !
 interface GigabitEthernet0/0/0/3
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !

!
mpls ldp
 log
  neighbor
 !
 igp sync delay on-session-up 20
 router-id 100.0.0.6
 session protection
 address-family ipv4
  discovery targeted-hello accept
  label
   local
    allocate for host-routes
   !
  !
 !
 interface GigabitEthernet0/0/0/1
 interface GigabitEthernet0/0/0/2
 interface GigabitEthernet0/0/0/3

!
