hostname tgw2
!
interface Loopback0
 ipv4 address 100.0.0.8 255.255.255.255
 ipv6 address 2001:cafe::8/128
!
interface GigabitEthernet0/0/0/1
 description private8 :: tgw2 -- tgw1
 ipv4 address 100.1.0.34/30
 ipv6 address 2001:cafe:1:8::2/64
!
interface GigabitEthernet0/0/0/2
 description private10 :: tgw2 -- tgw4
 ipv4 address 100.1.0.41/30
 ipv6 address 2001:cafe:1:a::1/64
!
interface GigabitEthernet0/0/0/3
 description private13 :: tgw2 -- jpe2
 ipv4 address 100.1.0.53/30
 ipv6 address 2001:cafe:1:d::1/64
!

!
router isis bb
 is-type level-2-only
 net 49.0001.0001.6400.0008.00
 address-family ipv4 unicast
  metric-style wide
 !
 interface Loopback0
  passive
  address-family ipv4 unicast
 !
!
 interface GigabitEthernet0/0/0/1
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !
 interface GigabitEthernet0/0/0/2
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !

!
mpls ldp
 log
  neighbor
 !
 igp sync delay on-session-up 20
 router-id 100.0.0.8
 session protection
 address-family ipv4
  discovery targeted-hello accept
  label
   local
    allocate for host-routes
   !
  !
 !
 interface GigabitEthernet0/0/0/1
 interface GigabitEthernet0/0/0/2

!
