hostname tgw3
!
interface Loopback0
 ipv4 address 100.0.0.9 255.255.255.255
 ipv6 address 2001:cafe::9/128
!
interface GigabitEthernet0/0/0/1
 description private9 :: tgw3 -- tgw1
 ipv4 address 100.1.0.38/30
 ipv6 address 2001:cafe:1:9::2/64
!
interface GigabitEthernet0/0/0/2
 description private11 :: tgw3 -- tgw4
 ipv4 address 100.1.0.45/30
 ipv6 address 2001:cafe:1:b::1/64
!
interface GigabitEthernet0/0/0/3
 description private14 :: tgw3 -- jpe3
 ipv4 address 100.1.0.57/30
 ipv6 address 2001:cafe:1:e::1/64
!

!
router isis bb
 is-type level-2-only
 net 49.0001.0001.6400.0009.00
 address-family ipv4 unicast
  metric-style wide
 !
 interface Loopback0
  passive
  address-family ipv4 unicast
 !
!
 interface GigabitEthernet0/0/0/2
  point-to-point
  address-family ipv4 unicast
   metric 1000 level 2
  !

!
mpls ldp
 log
  neighbor
 !
 igp sync delay on-session-up 20
 router-id 100.0.0.9
 session protection
 address-family ipv4
  discovery targeted-hello accept
  label
   local
    allocate for host-routes
   !
  !
 !
 interface GigabitEthernet0/0/0/2

!
